### ISSUE TITLE
Version number mis-match between the store and the app.

### ISSUE THREAD

**Issue by mscottsewell** [RolfBanziger/CrmDataExporter#1]
There's a mis-match between your version numbers and as a result the XrmToolbox plugin store always reports that your plugin needs to be updated - 

![image](https://cloud.githubusercontent.com/assets/6276300/20953510/4b1d8642-bc02-11e6-9902-bde75056ff2e.png)

**Comment by anothersphere** [comment]
Same here. Went mad trying to diagnose the issue.

**Comment by RolfBanziger** [comment]
Thanks for reporting, the current version should work now as intended.
